### ISSUE TITLE
NLog 5.0 Breaking changes

### ISSUE THREAD

**Issue by gpratt5** [jedipi/NLog.Targets.MicrosoftTeams#6]
This target fails when NLog initializes it, can't find the target of MicrosoftTeams

**Comment by snakefoot** [comment]
Maybe caused by this breaking change: [NLog Extensions assemblies will not load automatically](https://nlog-project.org/2021/08/25/nlog-5-0-preview1-ready.html#nlog-extensions-assemblies-will-not-load-automatically)

Have you tried using:
```xml
<nlog>
  <extensions>
    <add assembly="NLog.Targets.MicrosoftTeams" /> 
  </extensions>
</nlog>
```

Or the new NLog 5.0 style (Including extension-assembly in type-alias):

```xml
<target xsi:type="MicrosoftTeams, NLog.Targets.MicrosoftTeams" 
         name="msTeams" 
```

**Comment by jedipi** [comment]
@snakefoot is correct. both solutions works.

**Comment by gpratt5** [comment]
Closed with solution provided.
